tomcat:
  image: balamaci/tomcat7-jdk8
  volumes:
    - ./out:/opt/tomcat/logs

uitests:
  image: balamaci/ui-tests
  volumes:
    - .:/usr/src/app
    - ~/.m2:/root/.m2
  links:
    - tomcat
  ports:
    - 8080:8080
